import { Assets, Rectangle, Texture, TextureSource } from "pixi.js";
import type { CharacterState } from "@agentia/shared-types";
import type { FurnitureProp } from "./map/map";

// Pixel art must never be smoothed - keep every sprite crisp when scaled (docs request: real pixel-art assets).
TextureSource.defaultOptions.scaleMode = "nearest";

const SPRITE_BASE = "/sprites";
const REALISTIC_OFFICE_URL = "/office/agentia-office-realistic-v1.png";
const REALISTIC_CHARACTER_SHEET_URL = "/office/characters/agentia-characters-realistic-v2.png";
const REALISTIC_CHARACTER_COLUMNS = 5;
const REALISTIC_CHARACTER_ROWS = 2;

export type CharacterPose = "idle" | "working" | "error" | "completed" | "walk1" | "walk2";
/** Which way the character is drawn facing - "front" (toward the viewer) or "back" (walking away/up),
 * a pure rendering flourish driven by movement direction (like the wander stroll), not store state. */
export type Facing = "front" | "back";

/** STEP7: 5 appearance variants (short hair / long hair / glasses / bob / hoodie), generated by
 * tools/pixel-art/characters.mjs and picked deterministically from the employee's avatarVariant. */
export const CHARACTER_VARIANT_COUNT = 5;

const POSES: readonly CharacterPose[] = ["idle", "working", "error", "completed", "walk1", "walk2"];
const FACINGS: readonly Facing[] = ["front", "back"];

const FURNITURE_PROPS: readonly FurnitureProp[] = [
  "desk",
  "bookshelf",
  "plant",
  "server",
  "reception",
  "whiteboard",
  "cabinet",
  "conference_table",
  "monitor_wall",
  "couch",
  "vending_machine",
  "water_server",
  "trash",
];

function characterUrl(variant: number, pose: CharacterPose, facing: Facing, layer: "body" | "details"): string {
  return `${SPRITE_BASE}/char_v${variant}_${pose}_${facing}_${layer}.png`;
}

function propUrl(prop: FurnitureProp): string {
  return `${SPRITE_BASE}/prop_${prop}.png`;
}

const WINDOW_URL = `${SPRITE_BASE}/prop_window.png`;

function allAssetUrls(): string[] {
  const urls: string[] = [WINDOW_URL, REALISTIC_OFFICE_URL, REALISTIC_CHARACTER_SHEET_URL];
  for (const prop of FURNITURE_PROPS) urls.push(propUrl(prop));
  for (let variant = 0; variant < CHARACTER_VARIANT_COUNT; variant += 1) {
    for (const pose of POSES) {
      for (const facing of FACINGS) {
        urls.push(characterUrl(variant, pose, facing, "body"));
        urls.push(characterUrl(variant, pose, facing, "details"));
      }
    }
  }
  return urls;
}

let loadPromise: Promise<void> | null = null;

/**
 * PixiJS v8 no longer lazy-loads textures from URLs inside Texture.from - everything is fetched
 * up front through the Assets loader (with caching + dedupe). OfficeCanvas awaits this once
 * before mounting the stage, so every later texture lookup below is a synchronous cache hit.
 */
export function loadOfficeAssets(): Promise<void> {
  if (!loadPromise) {
    loadPromise = Assets.load(allAssetUrls()).then(() => undefined);
  }
  return loadPromise;
}

/** docs/09_CHARACTER_SYSTEM.md #3 states collapse onto a small set of sprite poses. */
const STATE_TO_POSE: Record<CharacterState, CharacterPose> = {
  idle: "idle",
  moving: "working",
  researching: "working",
  reading: "working",
  planning: "working",
  coding: "working",
  terminal: "working",
  testing: "working",
  deploying: "working",
  waiting: "idle",
  error: "error",
  completed: "completed",
};

export function poseForState(state: CharacterState): CharacterPose {
  return STATE_TO_POSE[state];
}

/** The texture pair for one employee's look; avatarVariant (0-7) folds onto the 5 generated variants. */
export function characterTextures(avatarVariant: number, pose: CharacterPose, facing: Facing): { body: Texture; details: Texture } {
  const variant = Math.abs(avatarVariant) % CHARACTER_VARIANT_COUNT;
  return {
    body: Assets.get<Texture>(characterUrl(variant, pose, facing, "body")),
    details: Assets.get<Texture>(characterUrl(variant, pose, facing, "details")),
  };
}

export function furnitureTexture(prop: FurnitureProp): Texture {
  return Assets.get<Texture>(propUrl(prop));
}

/** High-resolution architectural background generated for the realistic office presentation. */
export function realisticOfficeTexture(): Texture {
  const texture = Assets.get<Texture>(REALISTIC_OFFICE_URL);
  texture.source.scaleMode = "linear";
  return texture;
}

const realisticCharacterFrames = new Map<string, Texture>();

/**
 * Crops one front/back employee render from the generated 5x2 sheet. Keeping it as one source
 * image avoids ten separate network requests while still allowing Pixi to swap facing per frame.
 */
export function realisticCharacterTexture(avatarVariant: number, facing: Facing): Texture {
  const variant = Math.abs(avatarVariant) % REALISTIC_CHARACTER_COLUMNS;
  const key = `${variant}:${facing}`;
  const cached = realisticCharacterFrames.get(key);
  if (cached) return cached;

  const sheet = Assets.get<Texture>(REALISTIC_CHARACTER_SHEET_URL);
  sheet.source.scaleMode = "linear";
  const frameWidth = sheet.width / REALISTIC_CHARACTER_COLUMNS;
  const frameHeight = sheet.height / REALISTIC_CHARACTER_ROWS;
  const row = facing === "front" ? 0 : 1;
  const texture = new Texture({
    source: sheet.source,
    frame: new Rectangle(variant * frameWidth, row * frameHeight, frameWidth, frameHeight),
  });
  realisticCharacterFrames.set(key, texture);
  return texture;
}

/** Wall-mounted window prop for exterior-facing (topmost row) walls, untinted like furniture. */
export function windowTexture(): Texture {
  return Assets.get<Texture>(WINDOW_URL);
}
